-
  name: 'graphql - simple - endpoint'
  uriPattern: 'api/graphql/simple'
  defaults:
    '@package':    'Wwwision.GraphQL'
    '@controller': 'Standard'
    '@action':     'query'
    '@format':     'json'
    'endpoint':    'Ttree.Headless:Simple'
  httpMethods: [POST]
