-
  name: 'graphql - GraphiQL UI'
  uriPattern: 'api/content'
  defaults:
    '@package':    'Wwwision.GraphQL'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
    'endpoint':    'api/content'
  appendExceedingArguments: true
  httpMethods: [GET]

-
  name: 'graphql - simple - endpoint'
  uriPattern: 'api/content'
  defaults:
    '@package':    'Wwwision.GraphQL'
    '@controller': 'Standard'
    '@action':     'query'
    '@format':     'json'
    'endpoint':    'api/content'
  httpMethods: [POST]
